# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

robustweights <- function(X, delta = 15.0, zeta = 0.1) {
    .Call(`_RcvxBiclustr_robustweights`, X, delta, zeta)
}

robust_convex_bicluster <- function(X, W1, W2, V1, V2, Y1, Y2, Z1, Z2, E1, E2, max_iter, tol_abs, lambda, rho, wt_row, wt_col) {
    .Call(`_RcvxBiclustr_robust_convex_bicluster`, X, W1, W2, V1, V2, Y1, Y2, Z1, Z2, E1, E2, max_iter, tol_abs, lambda, rho, wt_row, wt_col)
}

robust_convex_bicluster_naive <- function(X, W1, W2, V1, V2, Y1, Y2, Z1, Z2, E1, E2, max_iter, tol_abs, lambda, rho, tau, wt_row, wt_col) {
    .Call(`_RcvxBiclustr_robust_convex_bicluster_naive`, X, W1, W2, V1, V2, Y1, Y2, Z1, Z2, E1, E2, max_iter, tol_abs, lambda, rho, tau, wt_row, wt_col)
}

